package phaser.input;

@:native("Phaser.Input")
extern class Input {
	function new (game:phaser.core.Game);
	var game:phaser.core.Game;
	var hitCanvas:Dynamic;
	var hitContext:Dynamic;
	var moveCallback:Dynamic;
	var moveCallbackContext:Dynamic;
	var pollRate:Float;
	var disabled:Bool;
	var multiInputOverride:Float;
	var position:phaser.geom.Point;
	var speed:phaser.geom.Point;
	var circle:phaser.geom.Circle;
	var scale:phaser.geom.Point;
	var maxPointers:Float;
	var currentPointers:Float;
	var tapRate:Float;
	var doubleTapRate:Float;
	var holdRate:Float;
	var justPressedRate:Float;
	var justReleasedRate:Float;
	var recordPointerHistory:Bool;
	var recordRate:Float;
	var recordLimit:Float;
	var pointer1:phaser.input.Pointer;
	var pointer2:phaser.input.Pointer;
	var pointer3:phaser.input.Pointer;
	var pointer4:phaser.input.Pointer;
	var pointer5:phaser.input.Pointer;
	var pointer6:phaser.input.Pointer;
	var pointer7:phaser.input.Pointer;
	var pointer8:phaser.input.Pointer;
	var pointer9:phaser.input.Pointer;
	var pointer10:phaser.input.Pointer;
	var activePointer:phaser.input.Pointer;
	var mousePointer:Dynamic;
	var mouse:phaser.input.Mouse;
	var keyboard:phaser.input.Keyboard;
	var touch:phaser.input.Touch;
	var mspointer:phaser.input.MSPointer;
	var gamepad:phaser.input.Gamepad;
	var onDown:phaser.core.Signal;
	var onUp:phaser.core.Signal;
	var onTap:phaser.core.Signal;
	var onHold:phaser.core.Signal;
	var interactiveItems:phaser.core.LinkedList;
	var _localPoint:phaser.geom.Point;
	var _pollCounter:Float;
	var _oldPosition:phaser.geom.Point;
	var _x:Float;
	var _y:Float;
	static var MOUSE_OVERRIDES_TOUCH:Float;
	static var TOUCH_OVERRIDES_MOUSE:Float;
	static var MOUSE_TOUCH_COMBINE:Float;
	function boot ():Void;
	function destroy ():Void;
	function setMoveCallback (callback:Dynamic, callbackContext:Dynamic):Void;
	function addPointer ():phaser.input.Pointer;
	function update ():Void;
	function reset (hard:Bool):Void;
	function resetSpeed (x:Float, y:Float):Void;
	function startPointer (event:Dynamic):phaser.input.Pointer;
	function updatePointer (event:Dynamic):phaser.input.Pointer;
	function stopPointer (event:Dynamic):phaser.input.Pointer;
	function getPointer (state:Bool):phaser.input.Pointer;
	function getPointerFromIdentifier (identifier:Float):phaser.input.Pointer;
	function getLocalPosition (displayObject:phaser.gameobjects.Sprite, pointer:phaser.input.Pointer):phaser.geom.Point;
	function hitTest (displayObject:Dynamic, pointer:phaser.input.Pointer, localPoint:phaser.geom.Point):Void;
	var x:Float;
	var y:Float;
	var pollLocked(default, null):Bool;
	var totalInactivePointers(default, null):Float;
	var totalActivePointers(default, null):Float;
	var worldX:Float;
	var worldY:Float;
}
