package phaser.tilemap;

@:native("Phaser.Tilemap")
extern class Tilemap {
	function new (game:phaser.core.Game, ?key:String, ?tileWidth:Float = 32, ?tileHeight:Float = 32, ?width:Float = 10, ?height:Float = 10);
	var game:phaser.core.Game;
	var key:String;
	var width:Float;
	var height:Float;
	var tileWidth:Float;
	var tileHeight:Float;
	var orientation:String;
	var version:Float;
	var properties:Dynamic;
	var widthInPixels:Float;
	var heightInPixels:Float;
	var layers:Dynamic;
	var tilesets:Dynamic;
	var tiles:Dynamic;
	var objects:Dynamic;
	var collideIndexes:Dynamic;
	var collision:Dynamic;
	var images:Dynamic;
	var currentLayer:Float;
	var debugMap:Dynamic;
	var _results:Dynamic;
	var _tempA:Float;
	var _tempB:Float;
	static var CSV:Float;
	static var TILED_JSON:Float;
	function create (name:String, width:Float, height:Float, tileWidth:Float, tileHeight:Float, ?group:phaser.core.Group):phaser.tilemap.TilemapLayer;
	function setTileSize (tileWidth:Float, tileHeight:Float):Void;
	function addTilesetImage (tileset:String, ?key:String, ?tileWidth:Float = 32, ?tileHeight:Float = 32, ?tileMargin:Float = 0, ?tileSpacing:Float = 0, ?gid:Float = 0):phaser.tilemap.Tileset;
	function createFromObjects (name:String, gid:Float, key:String, ?frame:Float, ?exists:Bool = true, ?autoCull:Bool = false, ?group:phaser.core.Group, ?CustomClass:Dynamic, ?adjustY:Bool = true):Void;
	function createLayer (layer:Float, ?width:Float, ?height:Float, ?group:phaser.core.Group):phaser.tilemap.TilemapLayer;
	function getIndex (location:Dynamic, name:String):Float;
	function getLayerIndex (name:String):Float;
	function getTilesetIndex (name:String):Float;
	function getImageIndex (name:String):Float;
	function getObjectIndex (name:String):Float;
	function setTileIndexCallback (indexes:Float, callback:Dynamic, callbackContext:Dynamic, ?layer:Float):Void;
	function setTileLocationCallback (x:Float, y:Float, width:Float, height:Float, callback:Dynamic, callbackContext:Dynamic, ?layer:Float):Void;
	function setCollision (indexes:Float, ?collides:Bool = true, ?layer:Float):Void;
	function setCollisionBetween (start:Float, stop:Float, ?collides:Bool = true, ?layer:Float):Void;
	function setCollisionByExclusion (indexes:Dynamic, ?collides:Bool = true, ?layer:Float):Void;
	function setCollisionByIndex (index:Float, ?collides:Bool = true, ?layer:Float, ?recalculate:Bool = true):Void;
	function getLayer (layer:Float):Float;
	function calculateFaces (layer:Float):Void;
	function getTileAbove (layer:Float, x:Float, y:Float):Void;
	function getTileBelow (layer:Float, x:Float, y:Float):Void;
	function getTileLeft (layer:Float, x:Float, y:Float):Void;
	function getTileRight (layer:Float, x:Float, y:Float):Void;
	function setLayer (layer:Float):Void;
	function hasTile (x:Float, y:Float, layer:Float):Bool;
	function putTile (tile:phaser.tilemap.Tile, x:Float, y:Float, ?layer:Float):phaser.tilemap.Tile;
	function putTileWorldXY (tile:phaser.tilemap.Tile, x:Float, y:Float, tileWidth:Float, tileHeight:Float, ?layer:Float):Void;
	function getTile (x:Float, y:Float, ?layer:Float):phaser.tilemap.Tile;
	function getTileWorldXY (x:Float, y:Float, ?tileWidth:Float, ?tileHeight:Float, ?layer:Float):phaser.tilemap.Tile;
	function copy (x:Float, y:Float, width:Float, height:Float, ?layer:Float):Dynamic;
	function paste (x:Float, y:Float, tileblock:Dynamic, ?layer:Float):Void;
	function swap (tileA:Float, tileB:Float, x:Float, y:Float, width:Float, height:Float, ?layer:Float):Void;
	function swapHandler (value:Float, index:Float):Void;
	function forEach (callback:Float, context:Float, x:Float, y:Float, width:Float, height:Float, ?layer:Float):Void;
	function replace (source:Float, dest:Float, x:Float, y:Float, width:Float, height:Float, ?layer:Float):Void;
	function random (x:Float, y:Float, width:Float, height:Float, ?layer:Float):Void;
	function shuffle (x:Float, y:Float, width:Float, height:Float, ?layer:Float):Void;
	function fill (index:Float, x:Float, y:Float, width:Float, height:Float, ?layer:Float):Void;
	function removeAllLayers ():Void;
	function dump ():Void;
	function destroy ():Void;
}
