package phaser.system;

@:native("Phaser.Device")
extern class Device {
	function new ();
	var game:phaser.core.Game;
	var desktop:Bool;
	var iOS:Bool;
	var cocoonJS:Bool;
	var ejecta:Bool;
	var android:Bool;
	var chromeOS:Bool;
	var linux:Bool;
	var macOS:Bool;
	var windows:Bool;
	var windowsPhone:Bool;
	var canvas:Bool;
	var file:Bool;
	var fileSystem:Bool;
	var localStorage:Bool;
	var webGL:Bool;
	var worker:Bool;
	var touch:Bool;
	var mspointer:Bool;
	var css3D:Bool;
	var pointerLock:Bool;
	var typedArray:Bool;
	var vibration:Bool;
	var getUserMedia:Bool;
	var quirksMode:Bool;
	var arora:Bool;
	var chrome:Bool;
	var epiphany:Bool;
	var firefox:Bool;
	var ie:Bool;
	var ieVersion:Float;
	var trident:Bool;
	var tridentVersion:Float;
	var mobileSafari:Bool;
	var midori:Bool;
	var opera:Bool;
	var safari:Bool;
	var webApp:Bool;
	var silk:Bool;
	var audioData:Bool;
	var webAudio:Bool;
	var ogg:Bool;
	var opus:Bool;
	var mp3:Bool;
	var wav:Bool;
	var m4a:Bool;
	var webm:Bool;
	var iPhone:Bool;
	var iPhone4:Bool;
	var iPad:Bool;
	var pixelRatio:Float;
	var littleEndian:Bool;
	var fullscreen:Bool;
	var requestFullscreen:String;
	var cancelFullscreen:String;
	var fullscreenKeyboard:Bool;
	function _checkOS ():Void;
	function _checkFeatures ():Void;
	function checkFullScreenSupport ():Void;
	function _checkBrowser ():Void;
	function _checkAudio ():Void;
	function _checkDevice ():Void;
	function _checkCSS3D ():Void;
	function canPlayAudio (type:String):Bool;
	function isConsoleOpen ():Bool;
}
