package phaser.physics.p2;

@:native("Phaser.Physics.P2")
extern class World {
	function new (game:phaser.core.Game, ?config:Dynamic);
	var game:phaser.core.Game;
	var world:Dynamic;
	var frameRate:Float;
	var useElapsedTime:Bool;
	var materials:Dynamic;
	var gravity:Dynamic;
	var bounds:Dynamic;
	var _wallShapes:Dynamic;
	var onBodyAdded:phaser.core.Signal;
	var onBodyRemoved:phaser.core.Signal;
	var onSpringAdded:phaser.core.Signal;
	var onSpringRemoved:phaser.core.Signal;
	var onConstraintAdded:phaser.core.Signal;
	var onConstraintRemoved:phaser.core.Signal;
	var onContactMaterialAdded:phaser.core.Signal;
	var onContactMaterialRemoved:phaser.core.Signal;
	var onBeginContact:phaser.core.Signal;
	var onEndContact:phaser.core.Signal;
	var _toRemove:Dynamic;
	var collisionGroups:Dynamic;
	var _collisionGroupID:Float;
	static var LIME_CORONA_JSON:Float;
	function removeBodyNextStep (body:phaser.physics.p2.Body):Void;
	function preUpdate ():Void;
	function enable (object:Dynamic, ?debug:Bool = false, ?children:Bool = true):Void;
	function enableBody (object:Dynamic, debug:Bool):Void;
	function setImpactEvents (state:Bool):Void;
	function setPostBroadphaseCallback (callback:Dynamic, context:Dynamic):Void;
	function postBroadphaseHandler (event:Dynamic):Void;
	function impactHandler (event:Dynamic):Void;
	function beginContactHandler (event:Dynamic):Void;
	function endContactHandler (event:Dynamic):Void;
	function setBoundsToWorld (?left:Bool = true, ?right:Bool = true, ?top:Bool = true, ?bottom:Bool = true, ?setCollisionGroup:Bool = true):Void;
	function setWorldMaterial (material:phaser.physics.p2.Material, ?left:Bool = true, ?right:Bool = true, ?top:Bool = true, ?bottom:Bool = true):Void;
	function updateBoundsCollisionGroup (?setCollisionGroup:Bool = true):Void;
	function setBounds (x:Float, y:Float, width:Float, height:Float, ?left:Bool = true, ?right:Bool = true, ?top:Bool = true, ?bottom:Bool = true, ?setCollisionGroup:Bool = true):Void;
	function clear ():Void;
	function destroy ():Void;
	function addBody (body:phaser.physics.p2.Body):Bool;
	function removeBody (body:phaser.physics.p2.Body):phaser.physics.p2.Body;
	function addSpring (spring:phaser.physics.p2.Spring):phaser.physics.p2.Spring;
	function removeSpring (spring:phaser.physics.p2.Spring):phaser.physics.p2.Spring;
	function createDistanceConstraint (bodyA:phaser.gameobjects.Sprite, bodyB:phaser.gameobjects.Sprite, distance:Float, ?maxForce:Float):phaser.physics.p2.DistanceConstraint;
	function createGearConstraint (bodyA:phaser.gameobjects.Sprite, bodyB:phaser.gameobjects.Sprite, ?angle:Float = 0, ?ratio:Float = 1):phaser.physics.p2.GearConstraint;
	function createRevoluteConstraint (bodyA:phaser.gameobjects.Sprite, pivotA:Array<Dynamic>, bodyB:phaser.gameobjects.Sprite, pivotB:Array<Dynamic>, ?maxForce:Float = 0):phaser.physics.p2.RevoluteConstraint;
	function createLockConstraint (bodyA:phaser.gameobjects.Sprite, bodyB:phaser.gameobjects.Sprite, ?offset:Array<Dynamic>, ?angle:Float = 0, ?maxForce:Float):phaser.physics.p2.LockConstraint;
	function createPrismaticConstraint (bodyA:phaser.gameobjects.Sprite, bodyB:phaser.gameobjects.Sprite, ?lockRotation:Bool = true, ?anchorA:Array<Dynamic>, ?anchorB:Array<Dynamic>, ?axis:Array<Dynamic>, ?maxForce:Float):phaser.physics.p2.PrismaticConstraint;
	function addConstraint (constraint:Dynamic):Dynamic;
	function removeConstraint (constraint:Dynamic):Dynamic;
	function addContactMaterial (material:phaser.physics.p2.ContactMaterial):phaser.physics.p2.ContactMaterial;
	function removeContactMaterial (material:phaser.physics.p2.ContactMaterial):phaser.physics.p2.ContactMaterial;
	function getContactMaterial (materialA:phaser.physics.p2.Material, materialB:phaser.physics.p2.Material):phaser.physics.p2.ContactMaterial;
	function setMaterial (material:phaser.physics.p2.Material, bodies:Dynamic):Void;
	function createMaterial (?name:String, ?body:phaser.physics.p2.Body):phaser.physics.p2.Material;
	function createContactMaterial (?materialA:phaser.physics.p2.Material, ?materialB:phaser.physics.p2.Material, ?options:Dynamic):phaser.physics.p2.ContactMaterial;
	function getBodies ():Dynamic;
	function getBody (object:Dynamic):Dynamic;
	function getSprings ():Dynamic;
	function getConstraints ():Dynamic;
	function hitTest (worldPoint:phaser.geom.Point, ?bodies:Dynamic, ?precision:Float = 5, ?filterStatic:Bool = false):Array<Dynamic>;
	function toJSON ():Dynamic;
	function createCollisionGroup (?object:phaser.core.Group):Void;
	function setCollisionGroup (object:phaser.core.Group, group:Dynamic):Void;
	function createSpring (bodyA:phaser.gameobjects.Sprite, bodyB:phaser.gameobjects.Sprite, ?restLength:Float = 1, ?stiffness:Float = 100, ?damping:Float = 1, ?restLength:Float = 1, ?stiffness:Float = 100, ?damping:Float = 1, ?worldA:Array<Dynamic>, ?worldB:Array<Dynamic>, ?localA:Array<Dynamic>, ?localB:Array<Dynamic>):phaser.physics.p2.Spring;
	function createBody (x:Float, y:Float, mass:Float, ?addToWorld:Bool = false, options:Dynamic, options:Bool, options:Bool, options:Bool, points:Dynamic):phaser.physics.p2.Body;
	function createParticle (x:Float, y:Float, mass:Float, ?addToWorld:Bool = false, options:Dynamic, options:Bool, options:Bool, options:Bool, points:Dynamic):Void;
	function convertCollisionObjects (map:phaser.tilemap.Tilemap, ?layer:Float, ?addToWorld:Bool = true):Dynamic;
	function clearTilemapLayerBodies (map:phaser.tilemap.Tilemap, ?layer:Float):Void;
	function convertTilemap (map:phaser.tilemap.Tilemap, ?layer:Float, ?addToWorld:Bool = true, ?optimize:Bool = true):Dynamic;
	function mpx (v:Float):Float;
	function pxm (v:Float):Float;
	function mpxi (v:Float):Float;
	function pxmi (v:Float):Float;
	var friction:Float;
	var restitution:Float;
	var applySpringForces:Bool;
	var applyDamping:Bool;
	var applyGravity:Bool;
	var solveConstraints:Bool;
	var time(default, null):Bool;
	var emitImpactEvent:Bool;
	var enableBodySleeping:Bool;
	var total(default, null):Float;
}
