package phaser.loader;

@:native("Phaser.Cache")
extern class Cache {
	function new (game:phaser.core.Game);
	var game:phaser.core.Game;
	var _canvases:Dynamic;
	var _images:Dynamic;
	var _textures:Dynamic;
	var _sounds:Dynamic;
	var _text:Dynamic;
	var _json:Dynamic;
	var _physics:Dynamic;
	var _tilemaps:Dynamic;
	var _binary:Dynamic;
	var _bitmapDatas:Dynamic;
	var _bitmapFont:Dynamic;
	var onSoundUnlock:phaser.core.Signal;
	static var CANVAS:Float;
	static var IMAGE:Float;
	static var TEXTURE:Float;
	static var SOUND:Float;
	static var TEXT:Float;
	static var PHYSICS:Float;
	static var TILEMAP:Float;
	static var BINARY:Float;
	static var BITMAPDATA:Float;
	static var BITMAPFONT:Float;
	static var JSON:Float;
	function addCanvas (key:String, canvas:Dynamic, context:Dynamic):Void;
	function addBinary (key:String, binaryData:Dynamic):Void;
	function addBitmapData (key:String, bitmapData:phaser.gameobjects.BitmapData):phaser.gameobjects.BitmapData;
	function addRenderTexture (key:String, texture:Dynamic):Void;
	function addSpriteSheet (key:String, url:String, data:Dynamic, frameWidth:Float, frameHeight:Float, ?frameMax:Float, ?margin:Float = 0, ?spacing:Float = 0):Void;
	function addTilemap (key:String, url:String, mapData:Dynamic, format:Float):Void;
	function addTextureAtlas (key:String, url:String, data:Dynamic, atlasData:Dynamic, format:Float):Void;
	function addBitmapFont (key:String, url:String, data:Dynamic, xmlData:Dynamic, ?xSpacing:Float = 0, ?ySpacing:Float = 0):Void;
	function addDefaultImage ():Void;
	function addMissingImage ():Void;
	function addText (key:String, url:String, data:Dynamic):Void;
	function addJSON (key:String, url:String, data:Dynamic):Void;
	function addImage (key:String, url:String, data:Dynamic):Void;
	function addSound (key:String, url:String, data:Dynamic, webAudio:Bool, audioTag:Bool):Void;
	function reloadSound (key:String):Void;
	function reloadSoundComplete (key:String):Void;
	function updateSound (key:String):Void;
	function decodedSound (key:String, data:Dynamic):Void;
	function getCanvas (key:String):Dynamic;
	function getBitmapData (key:String):phaser.gameobjects.BitmapData;
	function getBitmapFont (key:String):Dynamic;
	function getPhysicsData (key:String, ?object:String):Dynamic;
	function checkImageKey (key:String):Bool;
	function getImage (key:String):Dynamic;
	function getTilemap (key:String):Dynamic;
	function getFrameData (key:String):phaser.animation.FrameData;
	function updateFrameData (key:String, frameData:Float):Void;
	function getFrameByIndex (key:String):phaser.animation.Frame;
	function getFrameByName (key:String):phaser.animation.Frame;
	function getFrame (key:String):phaser.animation.Frame;
	function getTextureFrame (key:String):phaser.animation.Frame;
	function getTexture (key:String):phaser.gameobjects.RenderTexture;
	function getSound (key:String):phaser.sound.Sound;
	function getSoundData (key:String):Dynamic;
	function isSoundDecoded (key:String):Bool;
	function isSoundReady (key:String):Bool;
	function isSpriteSheet (key:String):Bool;
	function getText (key:String):Dynamic;
	function getJSON (key:String):Dynamic;
	function getBinary (key:String):Dynamic;
	function getKeys (?type:Float):Array<Dynamic>;
	function removeCanvas (key:String):Void;
	function removeImage (key:String):Void;
	function removeSound (key:String):Void;
	function removeText (key:String):Void;
	function removeJSON (key:String):Void;
	function removePhysics (key:String):Void;
	function removeTilemap (key:String):Void;
	function removeBinary (key:String):Void;
	function removeBitmapData (key:String):Void;
	function removeBitmapFont (key:String):Void;
	function destroy ():Void;
}
